[workspace]
members = ["vm_cpu", "vm_memory", "vm_assembler"]
default-members = ["vm_assembler"]
resolver = "2"

[workspace.dependencies]
vm_cpu = { path = "vm_cpu" }
vm_memory = { path = "vm_memory" }
