[workspace]
members = ["vm_cpu", "vm_assembler", "vm_lang"]
default-members = ["vm_lang"]
resolver = "2"

[workspace.dependencies]
vm_cpu = { path = "vm_cpu" }
vm_assembler = { path = "vm_assembler" }
