[package]
name = "vm_assembler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
tracing = { version = "0.1.41" }
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.19"
vm_cpu.workspace = true

[dev-dependencies]
insta = "1.43.1"
